version: "3.8"
 
services:

  starbucks-app:

    build:

      context: .

      dockerfile: Dockerfile

    container_name: starbucks-app

    ports:

      - "3000:3000"

    restart: unless-stopped
 
